name: pull-request

on:
  pull_request:

jobs:
  verification:
    runs-on: ubuntu-latest
    container: 
      image: malast/markdown-playground:latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Lint markdown files
      run: markdownlint-cli2 "**/*.md"
